### ISSUE TITLE
Data Shifted by One Trace Length

### ISSUE THREAD

**Issue by pjgoodling** [d-chambers/rg16#1]
Hello and thank you for sharing this important/ helpful code. We noticed while converting some data in the Farifield Continuous format (.fcnt) that the output was shifted by the length of one trace (in our case 2 minutes). The arrival of an earthquake P-wave was two minutes earlier than it should be. When comparing this code against the conversion code by ThomasLecoq (https://github.com/iceseismic/Fairfield-Receiver-Gather) we see that the data provided by this code is shifted up in time by 2 minutes.

![comparison](https://user-images.githubusercontent.com/26235106/35650724-151fee46-06ab-11e8-9336-c5b989d1bec3.png)

In what may be a related issue, one of the components (the vertical component) of the data is one trace shorter (2 minutes shorter) than the other 2 components.

![threecomponents](https://user-images.githubusercontent.com/26235106/35651051-48ce2798-06ac-11e8-8893-7557f97a9a8a.png)

Most likely the trace counting is getting tripped up during the quick merge procedure somehow, but I was unable to work it out on my own. Otherwise it works really fast and seems to handle quite large files very quickly which is greatly appreciated.

**Comment by d-chambers** [comment]
Hey @pjgoodling, thanks for the bug report.

Can you share any data/scripts that reproduce this issue so I can step through with a debugger and see exactly what is going on?

**Comment by pjgoodling** [comment]
I've attached a folder containing a Jupyter Notebook, the file for the data I plotted above. I suppose I should mention I am running Python 2.7, I'm not sure if that could be the source of any issues. Thanks!

[Rg16CodeTest.zip](https://github.com/d-chambers/rg16/files/1683688/Rg16CodeTest.zip)

**Comment by d-chambers** [comment]
I think I see whats going and have it fixed. Try using the code from branch "issue1" and see if it resolves the problem. If so, let me know and I will incorporate the fix into the master branch and bump the version.

**Comment by pjgoodling** [comment]
Yep that fix worked like a charm! The two conversion codes now match up (and match reality):

![comparison_fixed](https://user-images.githubusercontent.com/26235106/35680608-d9c2a284-0728-11e8-86d0-eec3f6dfac6a.png)

And the vertical component now has the last trace back. 

![threecomponents_fixed](https://user-images.githubusercontent.com/26235106/35680622-e0baf122-0728-11e8-9190-d6ad511356fa.png)

Thank you very much for the quick debugging! Cheers.
