### ISSUE TITLE
problem endtime of read_rg16(filename, headonly=True,merge=True)

### ISSUE THREAD

**Issue by xichaoqiang** [d-chambers/rg16#3]
Thanks for sharing the powerful package.

My fcnt time is very large.I want get the start and end time of each trace.

I try use read_rg16(filename, headonly=True,merge=True)

But the  samples number is null and endtime as same as starttime.

Can you fix it?

**Comment by d-chambers** [comment]
Hi,
This functionality has actually been fully integrated into obspy, and is more advanced than this package. You can just use obspy.read(filename, format='rg16'). Give that a try and open an issue on obspy if you have issues.

**Comment by xichaoqiang** [comment]
> Hi,
> This functionality has actually been fully integrated into obspy, and is more advanced than this package. You can just use obspy.read(filename, format='rg16'). Give that a try and open an issue on obspy if you have issues.

Thank you, I open a issue on Obspy. Can you help me check it?
